### PR TITLE
Timer addition

### PR DESCRIPTION
**Pull request by PDFowlers**
Everything currently "works" although it's not how I want it to be eventually. The task list and the timer are essentially separate entities but I would like to merge them in such a way that when I create a task I can associate a specific timer to it. 

But generally I just need some feedback overall on this cause I don't feel very good about it.

### CODE REVIEW

**Review by Riizade — COMMENTED** [review]
This looks reasonable to me
I'm not super familiar with tkinter, so there's some stuff I don't know

For example, `lb.delete(ANCHOR)`, I'm not sure how the variable `ANCHOR` gets populated or updated, so it seems like `deleteTask()` might be a little bit fragile, like, maybe if you have two listboxes, it might crash if you select something from another listbox then hit delete

but those are fine for now

the primary thing I think should be addressed is the organization of the file; there's just like a lot of stuff in no particular order, which makes it hard to read

a pretty common way to organize things is there's like one layout element per file

so you can make like a `task_list.py` file that defines the `lb` variable (maybe renamed to something more specific, like `task_list`), and it just defines the stuff needed to create the task list.

Then there's like a parent object like `window` or something that lays everything out together. And then the `main.py` file which is the actual entry point for the program.

That's just an example of how to organize it, but the point is that you want to describe broad detail in the code up front, and then leave the specifics for elsewhere if someone needs to dive into them. right now if I just read down the file, it's like, creating a bunch of elements and it's not clear how they fit together, and if I'm working on a bug related to like, reordering tasks, I'm not sure where to find that code because everything is mixed in. It'd be much clearer if there were a main file that says like "okay, here's the layout, put a listbox here and buttons here, etc" and then if you want to drill down on how a particular element is created, you can go the file where it's defined.

**Comment by PDFowlers** [comment]
Yeah I felt the organization was a problem whenever I needed to do something and had to scroll all over but I guess I wasn't sure exactly how it would look. Splitting the file up by widget type maybe is a good way to do it. I will work on that. Thanks!

**Comment by PDFowlers** [comment]
Ok so I have added the timer stuff enough to where I want to merge the files. But there are conflicts. I don't know how I made conflicts but can I just force a merge and make this the new main?

**Comment by Riizade** [comment]
gotta be careful to avoid conflicts

but yeah, in the future, when working on an individual project, the easiest way is sometimes to just force merge or delete master/main and replace it with the new branch

but when working in a group, I typically take my new branch, open a PR so I can see the changes, then make a new branch off of master/main, and manually copy the changes into the new branch so I have a clean working state guaranteed to be mergeable with master/main

otherwise you have to start using arcane git tools to rewrite history and ensure that your changes propagate correctly in a sea of other people's changes

**Pull request merged**
